---
output: pdf_document
---
Hi Jing + Martin,

(Attached is the markdown-processed version of the email - wouldn't it be nice if an email client could do that automagically...)

I figured out what was going on. Short answer: The stuff output in islandR is what we thought it was (i.e. it assumes that $P(j) = 1/j$ for all sources $j$) but isn't what the island model is using. i.e. my screwup.

The genomic bit of the island model gives us
$$
P(i | j, X_{ij}, \theta)
$$
where $X_{ij}$ is the observed STs $i$ on each source $j$ and $\theta$ are the genomic parameters (mutation/recombination/migration).

This is then used to estimate the likelihood of observing a given **human** isolate via the law of total probability to sum over the unknown source $j$
$$
P(h) = \sum_j P(i(h)|j) P(j)
$$
where $P(j)$ is the (unknown) probability that a random human isolate comes from source $j$, and $i(h)$ is the type of human isolate $h$.

Thus, we can estimate the unknown $P(j)$ that we're interested in by putting some prior on it (e.g. a $\mathsf{Dirichlet}(1,1,...1)$) and then using the likelihood over all human cases
$$
\begin{aligned}
P(H) &= \prod_{h \in H} P(i(h))\\
     &= \prod_{h \in H} \sum_j P(i(h)|j) P(j)
\end{aligned}
$$
to estimate $P(j)$ via Metropolis-Hastings.

Thus, the dumb Dirichlet prior which would have a huge influence on $P(j|i)$ is really on the attribution to human cases, which is informed by the distribution of STs we observe on the humans.

In the islandR code, I misread the code and ended up effectively setting $P(j) = 1/j$ and outputting $P(j|i)$ rather than just saving $P(i|j)$.

Jing: Given this, can you spot in the islandR processing code where this happens and fix it? Your graphs should then be showing $P(i|j)$ rather than $P(j|i)$.

I think continuing to look at the Dirchlet/Multinomial we talked about on Wednesday is still valuable to see how little information about $P(j)$, and thus $P(j|i)$ we have before we go and add in the human data. In particular, once you have some simulation results we should be able to add in the human data and run some M-H to estimate the $P(j)$'s.

Cheers,

Jonathan
