# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_lik <- function(humans, Phi, p) {
    .Call('_islandR_log_lik', PACKAGE = 'islandR', humans, Phi, p)
}

island <- function(isolates, beta_migration, gamma_mutation, gamma_recombination, X_mutation, X_recombination, samples = 100L, burnin = 10L, thin = 100L) {
    .Call('_islandR_island', PACKAGE = 'islandR', isolates, beta_migration, gamma_mutation, gamma_recombination, X_mutation, X_recombination, samples, burnin, thin)
}

