# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_lik <- function(humans, phi, p) {
    .Call('_islandR_log_lik', PACKAGE = 'islandR', humans, phi, p)
}

island <- function(isolates, niter = 10000L) {
    .Call('_islandR_island', PACKAGE = 'islandR', isolates, niter)
}

